# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: GitHub Metrics
on:
  # Schedule updates (each hour)
  schedule:
    - cron: "0 * * * *"
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          user: jrdagala
          template: classic
          plugin_activity: yes
          plugin_achievements: yes
          plugin_contributors: yes
          plugin_followup: yes
          plugin_habits: yes
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_people: yes
          plugin_repositories: yes
          plugin_stars: yes
          plugin_streak: yes
          plugin_traffic: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_languages_ignored: html,css,scss,less,stylus
          plugin_languages_colors: yes
          plugin_languages_threshold: 0%
          plugin_repositories_limit: 4
          plugin_repositories_sort: stars
          plugin_repositories_affiliations: owner,collaborator,organization_member
          plugin_stars_limit: 4
          plugin_streak_contributors: yes
          plugin_streak_contributors_limit: 4
          plugin_traffic_days: 14
          plugin_traffic_mode: daily